# Glibc is required for Factorio Server binaries to run
FROM ubuntu:24.04

ENV FACTORIO_VERSION="" \
    RCON_PASS=""

VOLUME /opt/fsm-data /opt/factorio/saves /opt/factorio/mods /opt/factorio/config

EXPOSE 80/tcp 34197/udp

RUN apt-get update && apt-get install -y curl tar xz-utils unzip jq && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

# Install the locally prepared FSM release bundle.
COPY build/factorio-server-manager-linux.zip /factorio-server-manager-linux.zip
RUN unzip /factorio-server-manager-linux.zip \
    && rm /factorio-server-manager-linux.zip \
    && mv factorio-server-manager fsm

COPY docker/entrypoint.sh /opt/entrypoint.sh
RUN sed -i 's/\r$//' /opt/entrypoint.sh && chmod 0755 /opt/entrypoint.sh

ENTRYPOINT ["/opt/entrypoint.sh"]
