FROM golang:1.26.8-alpine3.23@sha256:33ce311e5eecedee48ec1b84419c1306e9fbd71009f0d5c3f2a6904b579c1ecc AS build

RUN apk add --no-cache git make musl-dev nodejs npm zip mingw-w64-gcc

ENV FACTORIO_ROOT /go/src/factorio-server-manager

COPY docker/build-release.sh /usr/local/bin/build-release.sh
COPY ./ $FACTORIO_ROOT

RUN mkdir -p ${GOPATH}/bin
RUN chmod u+x /usr/local/bin/build-release.sh

WORKDIR $FACTORIO_ROOT

VOLUME /build
VOLUME $FACTORIO_ROOT

RUN ["/usr/local/bin/build-release.sh"]

FROM scratch as output
COPY --from=build ${FACTORIO_ROOT}/build/* .
